name: Combine Code Files

on:
  push:
    branches:
      - main  # یا شاخه‌ای که می‌خواهید این عملیات روی آن انجام شود
  pull_request:
    branches:
      - main  # یا شاخه‌ای که می‌خواهید این عملیات روی آن انجام شود

jobs:
  combine_files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Combine all files into one
      run: |
        # ایجاد یک فایل جدید برای ذخیره همه کدها
        echo "Combined Code Files" > combined_output.txt

        # ترکیب تمام فایل‌ها در یک فایل
        find . -type f -name "*.mql5" -exec cat {} >> combined_output.txt \;

    - name: Commit and push combined output file
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add combined_output.txt
        git commit -m "Add combined output file"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
