name: Combine Code Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  combine_files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Combine all files into one
      run: |
        # تنظیم Locale برای پشتیبانی از UTF-8
        export LC_ALL=en_US.UTF-8
        export LANG=en_US.UTF-8

        # ایجاد فایل نهایی با عنوان و مشخصات اولیه
        echo "//+------------------------------------------------------------------+" > combined_output.mq5
        echo "//| Combined Code Files - UTF-8                                       |" >> combined_output.mq5
        echo "//+------------------------------------------------------------------+" >> combined_output.mq5
        echo "" >> combined_output.mq5

        # ترکیب تمام فایل‌های .mq5 و .mqh به صورت UTF-8
        find . -type f \( -name "*.mq5" -o -name "*.mqh" \) -exec cat {} + >> combined_output.mq5

    - name: Commit and push combined output file
      run: |
        git config --global user.name "GitHub Actions"
        git config --global
